#!/bin/bash

# Publish FlowX image to a remote registry using Maple
#
# Provide the name of remote registry as an argument
#
maple image build --as-root flowx
maple container pour --image=flowx
maple container execute "python3 setup.py develop && python3 setup.py install && ./setup clean"
maple container commit --image=flowx
maple container rinse
maple push flowx $1
maple image delete flowx
