#!/bin/bash

#Development mode
if [ $1 = "develop" ]; then
    python3 setup.py develop --user

fi

#Install mode
if [ $1 = "install" ]; then
    python3 setup.py build
    python3 setup.py install --user
fi

#Clean after installation
if [ $1 = "clean" ]; then
    rm -rf *.egg-info
    rm -rf build dist
fi
