#!/usr/bin/env python3

"""Setup CLI script"""

import subprocess
import click


@click.group(name="setup")
def setup():
    """Setup toolkit for FlowX"""


@setup.command(name="develop")
def develop():
    """Development mode"""
    subprocess.run("python3 setup.py develop --user", shell=True, check=True)


@setup.command(name="install")
def install():
    """Installation command"""
    subprocess.run("python3 setup.py develop --user", shell=True, check=True)
    subprocess.run("python3 setup.py build", shell=True, check=True)
    subprocess.run("python3 setup.py install --user", shell=True, check=True)


@setup.command(name="clean")
def clean():
    """Clean installation artifacts"""
    subprocess.run("rm -rf *.egg-info build dist", shell=True, check=True)


if __name__ == "__main__":
    setup()
