#!/bin/bash

#
if [ $1 = "develop" ]; then
    #
    # Build the Python library in development mode
    #
    python3 setup.py develop --user

fi

#
if [ $1 = "install" ]; then
    #
    # Build the Python library in development mode
    #
    python3 setup.py build
    python3 setup.py install --user
fi

# Clean after installation
if [ $1 = "clean" ]; then
    rm -rf *.egg-info
    rm -rf build dist
fi
