name: examples

on:
  pull_request:
    branches: 
      - main
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'CITATION'

  push:
    branches: 
      - development
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'CITATION'

jobs:
  driven-cavity:
    name: "driven-cavity"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: akashdhruv/Maple/.github/actions/maple@main
    - name: Build Container
      run: |
          maple image build
    - uses: akashdhruv/BubbleBox/.github/actions/bubblebox@main
      with:
        base-image: flowx
    - uses: ./.github/actions/install
    - name: Run FlowX tests
      run: |
          maple container execute "cd examples/ins/lid_driven_cavity && python3 example.py"
          maple container clean
          maple image remove
