name: INS

on:
  pull_request:
    branches: 
      - main
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'CITATION'

jobs:

  Lidcav:
    name: "Lidcav"
    runs-on: ubuntu-latest
    steps:
    #- name: Login to Docker Hub
    #  run: |
    #      echo "::add-mask::${{secrets.DOCKER_HUB_PSK}}"
    #- uses: docker/login-action@v1
    #  with:
    #    username: ${{secrets.DOCKER_HUB_USERNAME}}
    #    password: ${{secrets.DOCKER_HUB_PSK}}
    - uses: actions/checkout@v2
    - uses: akashdhruv/Maple/.github/actions/maple@main
    - name: Build Container
      run: |
          maple image build flowx
    - uses: ./.github/actions/install
      with:
        image: flowx
    - name: Run FlowX tests
      run: |
          maple container pour --image=flowx
          maple container execute "cd examples/ins/lid_driven_cavity && python3 example.py"
          maple container rinse

  FlowCylinder:
    name: "FlowCylinder"
    runs-on: ubuntu-latest
    steps:
    #- name: Login to Docker Hub
    #  run: |
    #      echo "::add-mask::${{secrets.DOCKER_HUB_PSK}}"
    #- uses: docker/login-action@v1
    #  with:
    #    username: ${{secrets.DOCKER_HUB_USERNAME}}
    #    password: ${{secrets.DOCKER_HUB_PSK}}
    - uses: actions/checkout@v2
    - uses: akashdhruv/Maple/.github/actions/maple@main
    - name: Build Container
      run: |
          maple image build flowx
    - uses: ./.github/actions/install
      with:
        image: "flowx"
    - name: Run FlowX tests
      run: |
          maple container pour --image=flowx
          maple container execute "cd examples/ins/flow_cylinder && python3 example.py"
          maple container rinse

  FallCylinder:
    name: "FallCylinder"
    runs-on: ubuntu-latest
    steps:
    #- name: Login to Docker Hub
    #  run: |
    #      echo "::add-mask::${{secrets.DOCKER_HUB_PSK}}"
    #- uses: docker/login-action@v1
    #  with:
    #    username: ${{secrets.DOCKER_HUB_USERNAME}}
    #    password: ${{secrets.DOCKER_HUB_PSK}}
    - uses: actions/checkout@v2
    - uses: akashdhruv/Maple/.github/actions/maple@main
    - name: Build Container
      run: |
          maple image build flowx
    - uses: ./.github/actions/install
      with:
        image: flowx
    - name: Run FlowX tests
      run: |
          maple container pour --image=flowx
          maple container execute "cd examples/ins/fall_cylinder && python3 example.py"
          maple container rinse

  ViscoElastic:
    name: "ViscoElastic"
    runs-on: ubuntu-latest
    steps:
    #- name: Login to Docker Hub
    #  run: |
    #      echo "::add-mask::${{secrets.DOCKER_HUB_PSK}}"
    #- uses: docker/login-action@v1
    #  with:
    #    username: ${{ secrets.DOCKER_HUB_USERNAME }}
    #    password: ${{ secrets.DOCKER_HUB_PSK }}
    - uses: actions/checkout@v2
    - uses: akashdhruv/Maple/.github/actions/maple@main
    - name: Build Container
      run: |
          maple image build flowx
    - uses: ./.github/actions/install
      with:
        image: flowx
    - name: Run FlowX tests
      run: |
          maple container run "cd examples/ins/lid_driven_visco && python3 example.py"
