name: Publish

on:
  push:
    branches: 
      - development
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'CITATION'

jobs:

  Latest:
    name: "Latest"
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      run: |
          echo "::add-mask::${{secrets.DOCKER_HUB_PSK}}"
    - uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_HUB_USERNAME}}
        password: ${{secrets.DOCKER_HUB_PSK}}
    - uses: actions/checkout@v2      
    - uses: akashdhruv/Maple/.github/actions/maple@main
    - name: Build Container
      run: |
          maple image build flowx
    - uses: ./.github/actions/install
      with:
        image: flowx
    - name: Publish BubbleBox Image
      run: |
          maple push flowx ${{secrets.DOCKER_HUB_USERNAME}}/flowx:latest
