name: Publish
on:
  push:
    branches:
      - main
jobs:
  publish-image:
    name: "publish-image"
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      run: |
          echo "::add-mask::${{secrets.DOCKER_HUB_PSK}}"
    - uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_HUB_USERNAME}}
        password: ${{secrets.DOCKER_HUB_PSK}}
    - uses: actions/checkout@v2
    - uses: akashdhruv/Maple/.github/actions/maple@main
    - name: Publish FlowX Image
      run: |
          maple image build flowx --as-root
          maple container publish -I flowx
          maple push flowx ${{secrets.DOCKER_HUB_USERNAME}}/flowx:latest
