name: tests

on:
  pull_request:
    branches: 
      - main
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'CITATION'

  push:
    branches: 
      - development
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'CITATION'

jobs:
  flowx-container:
    name: "flowx-container"
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      run: |
          echo "::add-mask::${{secrets.DOCKER_HUB_PSK}}"
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PSK }}
    - uses: actions/checkout@v2
    - uses: akashdhruv/Maple/.github/actions/maple@main
    - name: Build Container
      run: |
          maple image build "local" ${{secrets.DOCKER_HUB_USERNAME}}/flowx:latest
    - uses: akashdhruv/BubbleBox/.github/actions/bubblebox@main
      with:
        image: "local"
    - uses: ./.github/actions/install
      with:
        image: "local"
    - name: Run FlowX tests
      run: |
          maple container pour --image=local
          maple container execute "python3 tests/container"
          maple container rinse
